completes api/articles/:article_id endpoint and tests
joemccaffrey-dev/nc_news_beProj pull request #3
Opened 2023-06-26 15:39 UTC by joemccaffrey-dev

2023-06-26 15:46 UTC, Dutton1990 commented on app/models/articles.models.js
> +
You don't need format here really, it's use is for inserting large amounts of data. You could use the standard $1

2023-06-26 15:48 UTC, Dutton1990 commented on __tests__/app.test.js
> +        delete body.article_id;
I'm not sure I understand the use of deleting article_id

2023-06-26 15:49 UTC, joemccaffrey-dev commented on __tests__/app.test.js
> +        delete body.article_id;
it's necessary to compare to the test data - article id only exists in the sql database.

2023-06-26 15:50 UTC, Dutton1990 commented on __tests__/app.test.js
> +  });
You can be really specific with this test - if you are going to articles/1 then i'd expect the article_id to be 1. 

You could also be really specific with the rest of the properties, how much you want to go into is upto you!

2023-06-26 15:51 UTC, joemccaffrey-dev commented on app/models/articles.models.js
> +
thanks, I'll change

2023-06-26 15:52 UTC, Dutton1990 commented on app/controllers/articles.controllers.js
> +        res.status(200).send(data);
You should send an object with a key and the data as the value

2023-06-26 15:56 UTC, Dutton1990 requested changes
Good start Joe! Now you can think about some error handling! 

What happens if you go to articles/999 or articles/notanumber? 

Once you've added this functionality please resubmit the PR and one of us will check it 😄

2023-06-26 15:58 UTC, joemccaffrey-dev commented on __tests__/app.test.js
> +  });
nice, have refactored to add article id of 1 to expectation object instead of the delete so it is testing this also.

2023-06-26 15:59 UTC, Dutton1990 commented on __tests__/app.test.js
> +        delete body.article_id;
Ahhh I see! Generally I'd avoid comparing to the test data for this reason - you'd also run into problems if the data has been manipulated in any way. 

These are your tests and you are writing them to build confidence that the server is handling as you expect.

You can grab the response and write yourself what you expect the returned data to look like! 

And we are reseeding the db after each test, so especially in this test case you can afford to be super specific about what you expect back!

2023-06-27 08:06 UTC, pippaamy requested changes
Good work, some changes to make and then pop in another pr :)

2023-06-27 08:06 UTC, pippaamy commented on __tests__/app.test.js
> +    const firstArticle = { ...data.articleData[0] };
I think you've overcomplicated this, we just need to see that body.id is equal to the article body. Having body equal to body doesn't check anything

2023-06-27 08:06 UTC, pippaamy commented on __tests__/app.test.js
> +      .get('/api/articles/chocolatecake')
this should be a 400

2023-06-27 08:06 UTC, pippaamy commented on app/controllers/articles.controllers.js
> +    .catch((e) => {
we want to have this in some error middleware rather than in the catch block

2023-06-27 08:06 UTC, pippaamy commented on app/endpointsList.json
> +    "description": "serves an object for the specified article id",
great!

2023-06-27 09:52 UTC, joemccaffrey-dev commented on app/controllers/articles.controllers.js
> +    .catch((e) => {
done this now

2023-06-27 09:53 UTC, caffreydev commented on __tests__/app.test.js
> +      .get('/api/articles/chocolatecake')
refactored this and added extra tests - app now spits out a 400 and appropriate message for an id parameter that is either not a number (chocolatecake) or a non integer number (3.2), with 404 only in valid ids that don't exist in the database (e.g. 99999)

2023-06-27 09:53 UTC, joemccaffrey-dev commented on __tests__/app.test.js
> +    const firstArticle = { ...data.articleData[0] };
ah good spot, thanks - I've changed it back to Expect(body).toEqual(firstarticle) where I had it initially (but seem to have changed by mistake at some point!).  Now it is fixed back to what it was originally and checks the app has served what was in the initial test data file for article 1.

2023-06-27 09:56 UTC, lewispricey approved these changes
Great work on this Joe, thanks for making the changes Pippa suggested!

Good to merge when you're ready 🚀

2023-06-27 10:20 UTC, merged