completes api/articles/:article_id/comments and associated tests
joemccaffrey-dev/nc_news_beProj pull request #5
Opened 2023-06-27 14:31 UTC by joemccaffrey-dev

2023-06-27 15:30 UTC, itskatherine requested changes
Hi Joe, some great work here, and solid happy path testing 💪 
However you need to correct your sad path testing and make sure your tests still pass when you do
Could you please resubmit this PR once you've had a look over these comments

2023-06-27 15:30 UTC, itskatherine commented on __tests__/app.test.js
> +        expect(body.comments).toBeSortedBy('created_at', { descending: true });
Nice use of jest-sorted 👍 
Great happy path tests!

2023-06-27 15:30 UTC, itskatherine commented on __tests__/app.test.js
> +          created_at: '2020-10-11T15:23:00.000Z',
To be thorough it would be good to check the general shape of all the comment objects (i.e. using a `forEach` check each comment using `expect.any(String)` etc) you expect back. 
However it would be valid in such a test to check all the comments have the `article_id` of exactly 6 (or whichever `article_id` you're testing)

2023-06-27 15:30 UTC, itskatherine commented on __tests__/app.test.js
> +      .catch((e) => {
For your error handling, you're using a .catch() block on your queries.
However I suspect you're getting false positives here, as an error isn't thrown, you instead respond with an object (that contains a status and an error message). The catch blocks aren't triggered, the expect statement isn't reached, and in jest, no fails mean a pass. To check this is the case, try putting an expect statement you know to be false in the catch block, like `expect(2).toBe(1)`, and see if your tests still pass.

This illustrates the importance of failing your tests before you pass them, so you know you haven't accidentally written un-failable tests.

You need to instead be using a .then() and checking the response object, instead.

2023-06-27 15:30 UTC, itskatherine commented on app/controllers/articles.controllers.js
> +      .send({ message: 'bad request: article id must be an integer' });
This error should be handled in your PSQL error handling controller 🔍 , by catching the error that happens when you give PSQL the wrong datatype

2023-06-28 07:32 UTC, joemccaffrey-dev commented on __tests__/app.test.js
> +          created_at: '2020-10-11T15:23:00.000Z',
now added a test doing this

2023-06-28 07:32 UTC, joemccaffrey-dev commented on __tests__/app.test.js
> +      .catch((e) => {
Thank you! now understand this a lot better - have now fixed this throughout the app

2023-06-28 07:32 UTC, joemccaffrey-dev commented on app/controllers/articles.controllers.js
> +      .send({ message: 'bad request: article id must be an integer' });
yep now done, as per comment above

2023-06-28 08:10 UTC, hevdevs approved these changes
All changes made look good! Happy for you to merge Joe 🎉

2023-06-28 08:17 UTC, merged